In [2]:
# Difference between Numpy Array and Python List

In [6]:
 import numpy as np

In [7]:
# calculating time to generate a list
%%timeit 

li = []

for num in range(1, 100+1):
    li.append(num**2)

UsageError: Line magic function `%%timeit` not found.


In [8]:
%timeit [i**2 for i in range(1, 100+1)]

19.3 µs ± 222 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
# calculating time to generate a np array
%timeit (np.arange(1,100+1))**2

1.03 µs ± 28.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Array

In [10]:
li = [1, 2, 3, 4]


# Creating numpy array
np_li = np.array(li)

# printing array 
print(np_li)

# printing array type
print(type(np_li))

[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
# creating empty list
l = []

# running for loop from 1 to 5
for i in range(1, 6):
    # Getting input from user in int format
    val = int(input("Enter Number :"))
    
    # appending the value to list l
    l.append(val)
    
# converting list l to numpy array and printing 
print(np.array(l))

np_l = np.array(l)

Enter Number :3
Enter Number :5
Enter Number :7
Enter Number :4
Enter Number :3
[3 5 7 4 3]


In [17]:
print(np_li.ndim)
print(np_l.ndim)

1
1


In [27]:
# Creating a 2d np array
arr2 = np.array([[1,2,4,5,6]])

# printing arr2
print(arr2)

# printing dimensions of arr2
print(arr2.ndim)

[[1 2 4 5 6]]
2


In [28]:
# Creating a 2d np array
arr2 = np.array([[1,2,4,5,6],[1,2,3,4,6]])

# printing arr2
print(arr2)

# printing dimensions of arr2
print(arr2.ndim)

[[1 2 4 5 6]
 [1 2 3 4 6]]
2


In [30]:
# Creating a 3x3 2D array
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# Creating a 3D array
arr3d = np.array([[[1,2,3],[4,5,6]]])
print(arr3d)
print(arr3d.ndim)

[[[1 2 3]
  [4 5 6]]]
3


In [42]:
# Creating n-dimensional array
arn = np.array([[1,2,3]], ndmin=10)
print(arn)
print(arn.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]]
10
